// Generates manual/reference/errors.md from the code (scripts/error-catalog.mjs)
// plus the hand-maintained meanings map (manual/reference/error-meanings.json).
// Fails when a code in the source has no meaning, or a meaning matches no code
// — both directions of drift break `npm run docs:generate` (and the unit
// guard, apps/server/test/error-catalog.test.ts, breaks in CI's verify:ci).
//
// A meaning is keyed by the bare code; where one code means different things
// in different owners, an "owner:code" entry overrides for that owner.
import { readFileSync, writeFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { checkCatalog, collectErrorCodes } from "./error-catalog.mjs";

const repoRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const meaningsPath = path.join(repoRoot, "manual/reference/error-meanings.json");
const outPath = path.join(repoRoot, "manual/reference/errors.md");

const catalog = collectErrorCodes(repoRoot);
const meanings = JSON.parse(readFileSync(meaningsPath, "utf8"));

const { missing, stale } = checkCatalog(catalog, meanings);
if (missing.length > 0 || stale.length > 0) {
  if (missing.length > 0)
    console.error(`error codes with no meaning in error-meanings.json:\n  ${missing.sort().join("\n  ")}`);
  if (stale.length > 0)
    console.error(`meanings whose code no longer exists in the source:\n  ${stale.sort().join("\n  ")}`);
  process.exit(1);
}

const rows = [...catalog.entries()]
  .sort(([a], [b]) => a.localeCompare(b))
  .map(([code, e]) => {
    const owners = [...e.owners].sort();
    const status = [...e.statuses].sort((a, b) => a - b).join(" / ");
    const meaning = owners
      .map((o) => meanings[`${o}:${code}`])
      .filter((m, i, arr) => m !== undefined && arr.indexOf(m) === i);
    const text = meaning.length > 0
      ? owners.length > 1 && meaning.length > 1
        ? owners.map((o) => `${o}: ${meanings[`${o}:${code}`] ?? meanings[code]}`).join("; ")
        : meaning.join("; ")
      : meanings[code];
    return `| \`${code}\` | ${status} | ${owners.join(", ")} | ${text} |`;
  });

const md = `# Error codes

> Generated by \`scripts/generate-errors.mjs\` from every \`PluginError\` and
> core \`{ error: "..." }\` response in the source, with meanings maintained in
> \`manual/reference/error-meanings.json\` — do not edit this page by hand.

Every refusal is a single snake_case code with no explanatory oracle: a caller
learns *that* they were refused, not which of several conditions failed. Refused
states that share a cause share a code (a pending, failed, or expired detective
report is all just "no report").

| Code | Status | Where | Meaning |
|---|---|---|---|
${rows.join("\n")}

## Conventions

- 4xx refusals on attack burn the cooldown (claim-before-transaction rule) —
  except \`unauthorized\` and \`self_attack\`, which are checked before the
  cooldown is claimed.
- Zod validation failures on bodies, query strings and route params return a
  clean 400 (\`invalid_request\`) before any database read.
`;

writeFileSync(outPath, md);
console.log(`generated errors.md: ${catalog.size} codes`);
